name: 📦 Deploy on release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo Connected OK"

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /root/fm01beta
          git pull origin main
          echo "Pulled successfully"
          tmux has-session -t beta 2>/dev/null && tmux kill-session -t beta
          echo "Killed beta"
          tmux new -d -s beta 'source ./.venv/bin/activate && python3.12 -OO main.py'
          tmux set-option -t beta remain-on-exit on
          echo "Bot is running"
          EOF
